services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: root#root
      MARIADB_DATABASE: stretch_db
      MARIADB_USER: stretchapp
      MARIADB_PASSWORD: root#root

#   sveltekit:
#   build: ./
#    ports:
#     - "3000:3000"
#   environment:
#     - NODE_ENV=production
  
  auth-server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: stretchapp
      DB_PASSWORD: root#root
      DB_DATABASE: stretch_db
    develop:
      watch:
        - action: rebuild
          path: ./server
          ignore:
            - node_modules/


volumes:
  mariadb_data:
